from pony.orm import *
from classes.enumDefinitions import *
import datetime

db = Database()


class Printer(db.Entity):
    name = Required(str, unique=True)
    """Human friendly name for printer. Example: 'Prusa01' """
    model = Required(str)
    """Model of the printer."""
    ip = Required(str, unique=True)
    """IP address to send print files to and query print status from."""
    api_key = Required(str)
    """Required API key to communicate with printer."""
    stream_ip = Optional(str)
    """Optional IP address for a streaming camera."""
    material_type = Optional(str)
    material_color = Optional(str)
    material_density = Required(float)
    enabled = Required(bool)
    print_jobs = Set('PrintJob')
    """Used to relate print jobs to this printer. Not an actual field, just a Pony ORM thing"""

    @staticmethod
    @db_session
    def Get_All():
        query_result = select(p for p in Printer)
        printers = []
        for p in query_result:
            printers.append(p)
        return printers

    @staticmethod
    @db_session
    def Get_All_Enabled():
        query_result = select(p for p in Printer if p.enabled is True)
        printers = []
        for p in query_result:
            printers.append(p)
        return printers

    @staticmethod
    @db_session
    def Get_All_By_Type(printer_model: PrinterModel):
        query_result = select(p for p in Printer if p.model == printer_model.name)
        printers = []
        for p in query_result:
            printers.append(p)
        return printers

    @staticmethod
    def Map_Request(printer, form_data):
        """
        Maps request data to a printer object.
        """
        printer.name = form_data['name']
        printer.model = PrinterModel(int(form_data['model'])).name
        printer.ip = form_data['ip']
        printer.api_key = form_data['api_key']
        printer.stream_ip = form_data['stream_ip']
        printer.material_type = form_data['material_type']
        printer.material_color = form_data['material_color']
        try:
            printer.material_density = float(form_data['material_density'])
        except:
            printer.material_density = None
        printer.enabled = form_data['enabled'] == 'true'


    @staticmethod
    @db_session
    def Add_From_Request(form_data):
        """
        Maps request data to a printer object.
        """
        name = form_data['name']
        model = PrinterModel(int(form_data['model'])).name
        ip = form_data['ip']
        api_key = form_data['api_key']
        stream_ip = form_data['stream_ip']
        material_type = form_data['material_type']
        material_color = form_data['material_color']
        try:
            material_density = float(form_data['material_density'])
        except:
            material_density = None
        enabled = form_data['enabled'] == 'true'

        Printer(name=name, model=model, ip=ip,api_key=api_key,stream_ip=stream_ip,material_type=material_type,material_color=material_color, material_density=material_density, enabled=enabled)


class PrintJob(db.Entity):
    printed_on = Optional(Printer)
    """Printer this job was processed on."""
    job_id = Required(int)
    """ID from the job submission system. We use Jira. This will be the unique ID generated by jira. Only digits in our case."""
    job_name = Optional(str)
    """Optional custom job name from the submission system. We use PR-#### formatted names."""
    downloaded_at = Required(datetime.datetime)
