from pony.orm import *
from classes.enumDefinitions import *

db = Database()


class Printer(db.Entity):

    name = Required(str, unique=True)
    """Human friendly name for printer. Example: 'Prusa01' """
    model = Required(PrinterModel)
    """Model of the printer."""
    ip = Required(str, unique=True)
    """IP address to send print files to and query print status from."""
    api_key = Required(str)
    """Required API key to communicate with printer."""
    stream_ip = Optional(str)
    """Optional IP address for a streaming camera."""
    material_type = Optional(str)
    material_color = Optional(str)
    material_density = Optional(float)
    print_jobs = Set('PrintJob')
    """Used to relate print jobs to this printer."""


class PrintJob(db.Entity):
    printed_on = Optional(Printer)
    """Printer this job was processed on."""
    job_id = Required(int)
    """ID from the job submission system. We use Jira. This will be the unique ID generated by jira. Only digits in our case."""
    job_name = Optional(str)
    """Optional custom job name from the submission system. We use PR-#### formatted names."""
